version: '3'

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword123
      MYSQL_DATABASE: ets
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ../../backend/event-ticketing-system
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ets
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: P@ssword123

  frontend:
    build: ../../frontend/event-ticketing-system
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
